====================EDA=====================
   
    1- pandas- for data frame work(read,write,modification)
    
    2- numpy- for math operation
    
    3- matplotlib- for plotting graphs
    
    4- seaborn- for plot graphs
    
    5- bokhe- plot graphs
    
    6- plotly- plot graphs

=================ml============

7- scikit learn(sklearn)-  ml model available

8- stats - statistical models

============data retrival from sql scrapping ==============

9- sqlite- connect with database

10-beautiful soap- scrap the data from website

11- websocket- scrapping

=============deep learning=============

12- tensorflow- google

13- keras- dl models

14-OpenCV- image op

15- Pillow(PIL)- image op

16- Pytorch- facebook

17- pretrained models- VGG16, Mobilenet, RESNET, RCNN, MASKRCNN, FASTERCNN, YOLO

**================natural language processing====================**

18- NLTK- natural language process tool kit

19- Scipy

20- Word2vec- how words will be converted into vector

21- GloVE- 

22- Wordcloud

**=====================Huggingface===============**

23- Trsansformers- BERT (google property)(bidirectional encorder representation of transformer)

**============genai models==================**

24- openAI+microsoft- GPT models

25- google- gemini

26- amazon- q

27- meta- meta AI 

28- Apple- 

llama= meta

**==============langchain===============**

29- LangChain- it is a frame work that links with all the companies so that we no need to remember all the packages of different companies.

**===============deployment===============**

30- flask

31- Streamlit

32- Django

**======================MLops==========================**

33- Mlflow

34- Kubeflow

35- Azure Ai services- azure packages
    
36- GCP- GCP paclkages

**step**

1- create a dataframe:
    
    -we can create a dataframe using list
    
    -we can create a dataframe using dictionary

In [1]:
import pandas as pd

In [2]:
d=pd.DataFrame()
d

Empty DataFrame
Columns: []
Index: []

In [3]:
type(d)

pandas.core.frame.DataFrame

In [4]:
name=['sk','ak','dm']
d=pd.DataFrame(name, columns=['Names'])
d

Names
0    sk
1    ak
2    dm

In [5]:
name=['sk','ak','dm']
age=[23,24,22]
data=zip(name,age)
d=pd.DataFrame(data)
d

0   1
0  sk  23
1  ak  24
2  dm  22

In [6]:
**step 3 **
- provide column names

SyntaxError: invalid syntax (33391614.py, line 1)

In [ ]:
name=['sk','ak','dm']
d=pd.DataFrame(name)
d

In [ ]:
name=['sk','ak','dm']
age=[23,24,22]
data=zip(name,age)
col=['names','age']
d=pd.DataFrame(data, columns=col)
d

In [ ]:
**step 4**
-  providing index

In [ ]:
name=['sk','ak','dm']
age=[23,24,22]
data=zip(name,age)
d=pd.DataFrame(data, columns=['name','age'], index=['a','b','c'])
d

In [ ]:
name=['sk','ak','dm']
age=[23,24,22]
city=['hyd','ban','mum']
data=zip(name,age)
d=pd.DataFrame(data, columns=['name','age'], index=city)
d

In [ ]:
**step 5**

-  add a new column in existing DataFrame

-  if want to add new columns check how many rows are their

-  ex below dataframe has three rows so the new column also should also have three rows

-  suppose a new col sal is created

-  sal=[100,200,300]

- **syn : dataframe[column]= list of values**
    
-  d['salary']=sal

In [ ]:
name=['sk','ak','dm']
age=[23,24,22]
data=zip(name,age)
d=pd.DataFrame(data)
sal=[eval(input('enter salary ')) for i in range (len(name))]
d['salary']=sal
d

In [ ]:
**use case 1**

- create a empty dataframe first

-create 3 list using list comprehension

-l1= a values from 1 to 10

- l2= square from 1 to 10

- l3=cube from i to 10


In [ ]:
l1=[i for i in range(1,11)]
l2=[i**2 for i in range(1,11)]
l3=[i**3 for i in range(1,11)]
data=zip(l1,l2,l3)
d=pd.DataFrame(data)
d['square']=l2
print(d.to_string(index=False))


In [ ]:
**step 6**

- update the existing column

-  create a new list  

-  while updating the existing column

- we need to provide already exisyed column name only

- df[2]= new values



In [ ]:
name=['sk','ak','dm']
age=[23,24,22]
data=zip(name,age)
d=pd.DataFrame(data)
sal=[eval(input('enter salary ')) for i in range (len(name))]
d[1]=sal
d

** step 7-  Drop the column**

if you want to drop a specific column

- we will use drop method

- we already know about differencede between keywords and methods

- keywords will use directly

- methods will use with corresponding dataframe

- method name is: drop

*df1.drop()*

- column: which column you want to drop 

- axis : represents the specific value is a row or column

    - axis=0 means row
    - axis=1 means column
    - by default axis=0
 
- inplace:will provide overwrite the dataframe or not
    - inplace =True ,this indicates overwrite the dataframe
    - inplace =False ,this indicates the modified dataframe will be use when u provide new variable for the operation

In [11]:
d.columns

Index([0, 1, 2, 'square'], dtype='object')

**step 8 - drop the row**

**drop the row**

- drop the column and drop the rows both are similar only

- the only difference is axis

    - axis=0 represents rows

    - by default axis=0 availabe

    - which means if we provide any value,it will represent row only


In [41]:
l1=[i for i in range(1,11)]
l2=[i**2 for i in range(1,11)]
l3=[i**3 for i in range(1,11)]
data=zip(l1,l2,l3)
d=pd.DataFrame(data)
d['square']=l2
d['number']=l1
d['cube']=l3

print(d.to_string(index=False))

 0   1    2  square  number  cube
 1   1    1       1       1     1
 2   4    8       4       2     8
 3   9   27       9       3    27
 4  16   64      16       4    64
 5  25  125      25       5   125
 6  36  216      36       6   216
 7  49  343      49       7   343
 8  64  512      64       8   512
 9  81  729      81       9   729
10 100 1000     100      10  1000


In [8]:
d.drop(5)
#if we run this we will get error
#by default axis=0 which represents about rows
#but square is column
#if want to drop a roe, provide the row index

0    1     2  square
0   1    1     1       1
1   2    4     8       4
2   3    9    27       9
3   4   16    64      16
4   5   25   125      25
6   7   49   343      49
7   8   64   512      64
8   9   81   729      81
9  10  100  1000     100

In [9]:
d.drop([4,8])

0    1     2  square
0   1    1     1       1
1   2    4     8       4
2   3    9    27       9
3   4   16    64      16
5   6   36   216      36
6   7   49   343      49
7   8   64   512      64
9  10  100  1000     100

In [10]:
d.drop([4,8],axis=1)
#axis =1 implies column

KeyError: '[4, 8] not found in axis'

**step 9 - how to select the column**

In [12]:
d['square']

# series type
# no column name displayed
# whenever you see this type : series type

0      1
1      4
2      9
3     16
4     25
5     36
6     49
7     64
8     81
9    100
Name: square, dtype: int64

In [13]:
d[['square']]

#data frame type

square
0       1
1       4
2       9
3      16
4      25
5      36
6      49
7      64
8      81
9     100

In [21]:
type(d[['square']])

pandas.core.frame.DataFrame

In [17]:
type(d['square'])

pandas.core.series.Series

In [18]:
d.square


0      1
1      4
2      9
3     16
4     25
5     36
6     49
7     64
8     81
9    100
Name: square, dtype: int64

In [26]:
col=['square', 'number']
d[col]

square  number
0       1       1
1       4       2
2       9       3
3      16       4
4      25       5
5      36       6
6      49       7
7      64       8
8      81       9
9     100      10

In [27]:
d['number'].values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

- all values comes in an array

- array means it is a list of elements only using numpy package 

-generally elements present in 4 ways

    - list: array with numpy package
    
    - numpy array: array with numpy package
        
    - tensors: tensorflow package
        
    - torch: pytorch package

In [28]:
l1=[1,2,3,4]
l1

[1, 2, 3, 4]

In [29]:
import numpy as np
np.array(l1)

array([1, 2, 3, 4])

In [31]:
l1=[1,5,5]
l2=[2,5,80]
l1+l2

[1, 5, 5, 2, 5, 80]

In [32]:
li1=np.array(l1)
li2=np.array(l2)
li1+li2

array([ 3, 10, 85])

In [33]:
d['NUMBER']=d['number'].values

In [34]:
d

0    1     2  square  number  cube  NUMBER
0   1    1     1       1       1     1       1
1   2    4     8       4       2     8       2
2   3    9    27       9       3    27       3
3   4   16    64      16       4    64       4
4   5   25   125      25       5   125       5
5   6   36   216      36       6   216       6
6   7   49   343      49       7   343       7
7   8   64   512      64       8   512       8
8   9   81   729      81       9   729       9
9  10  100  1000     100      10  1000      10

In [ ]:
**step 10**

-df we can save in two formats

    -csv: comma seperated value
    -xlsx- excel format
- inorder to save any data

    -when you want to save

In [43]:
d.to_csv('data1.csv')
d.to_excel('data.xlsx')

**step 11**

**how to read a dataframe**

In [44]:
import pandas as pd
pd.read_csv('data1.csv')

Unnamed: 0   0    1     2  square  number  cube
0           0   1    1     1       1       1     1
1           1   2    4     8       4       2     8
2           2   3    9    27       9       3    27
3           3   4   16    64      16       4    64
4           4   5   25   125      25       5   125
5           5   6   36   216      36       6   216
6           6   7   49   343      49       7   343
7           7   8   64   512      64       8   512
8           8   9   81   729      81       9   729
9           9  10  100  1000     100      10  1000

In [46]:
pd.read_excel('data.xlsx')

Unnamed: 0   0    1     2  square  number  cube
0           0   1    1     1       1       1     1
1           1   2    4     8       4       2     8
2           2   3    9    27       9       3    27
3           3   4   16    64      16       4    64
4           4   5   25   125      25       5   125
5           5   6   36   216      36       6   216
6           6   7   49   343      49       7   343
7           7   8   64   512      64       8   512
8           8   9   81   729      81       9   729
9           9  10  100  1000     100      10  1000

In [48]:
import os
os.getcwd()

'C:\\Users\\user\\datascience\\EDA'

In [ ]:
#unamed because extra column is created while saving

**step 12**

to avoid extra column(index column)

In [53]:
d.to_csv('data1.csv',index= False)
d.to_excel('data.xlsx',index=False)
pd.read_csv('data1.csv')
#print(pd.read_excel('data.xlsx'))

0    1     2  square  number  cube
0   1    1     1       1       1     1
1   2    4     8       4       2     8
2   3    9    27       9       3    27
3   4   16    64      16       4    64
4   5   25   125      25       5   125
5   6   36   216      36       6   216
6   7   49   343      49       7   343
7   8   64   512      64       8   512
8   9   81   729      81       9   729
9  10  100  1000     100      10  1000